-- Import course itineraries from:
-- /Users/leonardobarreto/projects/contracts/Imports/EXPEDIENTES ALUMNOS - APP(Cursos).csv
-- Usage example:
-- mysql -u root -D contracts_app < contracts-sql/scripts/import-course-itineraries-from-csv.sql

USE contracts_app;

CREATE TABLE IF NOT EXISTS course_itineraries (
  course_code VARCHAR(50) NOT NULL,
  itinerary_name VARCHAR(190) NOT NULL,
  PRIMARY KEY (course_code)
) ENGINE=InnoDB;

INSERT INTO course_itineraries (course_code, itinerary_name)
VALUES
  ('25EMHA01','AYUDANTE DE CAMARERO'),
  ('25EMHA02','AYUDANTE DE COCINA'),
  ('25EMHA03','AYUDANTE DE COCINA'),
  ('25EMHA04','AYUDANTE DE COCINA'),
  ('25EMHA05','AYUDANTE DE CAMARERO'),
  ('25EMHA06','AYUDANTE DE COCINA'),
  ('25EMHA07','AYUDANTE DE COCINA'),
  ('25EMHA08','ATENCION AL CLIENTE EN BARRA Y TIENDA'),
  ('25EMHA09','CdP OPERACIONES BÁSICAS COCINA'),
  ('25EMHA10','COCINA AVANZADA'),
  ('25EMHA11','SERVICIO DE SALA ESPECIALIZADO'),
  ('25EMHA13','AYUDANTE DE CAMARERO'),
  ('25EMHA14','OPERARIO DE DESPIECE'),
  ('25EMHA15','AYUDANTE DE COCINA'),
  ('25EMHA16','AYUDANTE DE CATERING'),
  ('25EMHA17','OPERARIO DE CARNICERIA'),
  ('25EMHA18','OPERARIO DE PESCADERIA'),
  ('25EMHA20','AYUDANTE BARRA Y SALA PASTELERÍA'),
  ('25EMHA21','AYUDANTE DE COCINA'),
  ('25EMHA22','AYUDANTE DE COCINA'),
  ('25EMHA23','AYUDANTE BARRA PASTELERIA'),
  ('25EMHA24','AYUDANTE BARRA PASTELERIA'),
  ('25EMHA25','AYUDANTE CAMARERO'),
  ('25EMHA26','AYUDANTE PANADERÍA Y PASTELERÍA'),
  ('25EMHA27','AYUDANTE PANADERÍA Y PASTELERÍA'),
  ('25EMHA28','OPERARIO DE CARNICERIA'),
  ('25EMHA29','AYUDANTE COCINA'),
  ('26EMHA01','AYUDANTE COCINA'),
  ('26EMHA02','AYUDANTE COCINA'),
  ('26EMHA03','AYUDANTE PANADERÍA Y PASTELERÍA'),
  ('26EMHA04','AYUDANTE SALA Y BARRA'),
  ('26EMHA05','AYUDANTE DE CARNICERIA'),
  ('26EMHA06','AYUDANTE COCINA Y SERVICIO DE MOSTRADOR'),
  ('26EMHA07','ATENCIÓN AL CLIENTE EN SERVICIO DE BARRA Y TIENDA'),
  ('26EMHA08','ELABORACION DE PLATOS, FAST FOOD Y CATERING'),
  ('26EMHA09','AYUDANTE PANADERIA Y PASTELERIA'),
  ('26EMHA10','AYUDANTE SALA Y BARRA'),
  ('26EMHA11','AYUDANTE COCINA'),
  ('26EMHA12','OPERARIO DE CARNICERIA')
ON DUPLICATE KEY UPDATE
  itinerary_name = VALUES(itinerary_name);

SELECT
  COUNT(*) AS total_course_itineraries
FROM course_itineraries;
